using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class JointProgression
{
    private double[] expertMovementHipCenterX;
    private double[] expertMovementHipCenterY;
    private double[] expertMovementHipCenterZ;
    private double[] expertMovementSpineX;
    private double[] expertMovementSpineY;
    private double[] expertMovementSpineZ;
    private double[] expertMovementNeckX;
    private double[] expertMovementNeckY;
    private double[] expertMovementNeckZ;
    private double[] expertMovementHeadX;
    private double[] expertMovementHeadY;
    private double[] expertMovementHeadZ;
    private double[] expertMovementShoulderCenterX;
    private double[] expertMovementShoulderCenterY;
    private double[] expertMovementShoulderCenterZ;
    private double[] expertMovementShoulderLeftX;
    private double[] expertMovementShoulderLeftY;
    private double[] expertMovementShoulderLeftZ;
    private double[] expertMovementElbowLeftX;
    private double[] expertMovementElbowLeftY;
    private double[] expertMovementElbowLeftZ;
    private double[] expertMovementWristLeftX;
    private double[] expertMovementWristLeftY;
    private double[] expertMovementWristLeftZ;
    private double[] expertMovementHandLeftX;
    private double[] expertMovementHandLeftY;
    private double[] expertMovementHandLeftZ;
    private double[] expertMovementShoulderRightX;
    private double[] expertMovementShoulderRightY;
    private double[] expertMovementShoulderRightZ;
    private double[] expertMovemenElbowRightX;
    private double[] expertMovemenElbowRightY;
    private double[] expertMovemenElbowRightZ;
    private double[] expertMovementWristRightX;
    private double[] expertMovementWristRightY;
    private double[] expertMovementWristRightZ;
    private double[] expertMovementHandRightX;
    private double[] expertMovementHandRightY;
    private double[] expertMovementHandRightZ;
    private double[] expertMovementHipLeftX;
    private double[] expertMovementHipLeftY;
    private double[] expertMovementHipLeftZ;
    private double[] expertMovementKneeLeftX;
    private double[] expertMovementKneeLeftY;
    private double[] expertMovementKneeLeftZ;
    private double[] expertMovementAnkcleLeftX;
    private double[] expertMovementAnkcleLeftY;
    private double[] expertMovementAnkcleLeftZ;
    private double[] expertMovementFootLeftX;
    private double[] expertMovementFootLeftY;
    private double[] expertMovementFootLeftZ;
    private double[] expertMovementHipRightX;
    private double[] expertMovementHipRightY;
    private double[] expertMovementHipRightZ;
    private double[] expertMovementKneeRightX;
    private double[] expertMovementKneeRightY;
    private double[] expertMovementKneeRightZ;
    private double[] expertMovementAnckleRightX;
    private double[] expertMovementAnckleRightY;
    private double[] expertMovementAnckleRightZ;
    private double[] expertMovementFootRightX;
    private double[] expertMovementFootRightY;
    private double[] expertMovementFootRightZ;

    private double[] amatureMovementHipCenterX;
    private double[] amatureMovementHipCenterY;
    private double[] amatureMovementHipCenterZ;
    private double[] amatureMovementSpineX;
    private double[] amatureMovementSpineY;
    private double[] amatureMovementSpineZ;
    private double[] amatureMovementNeckX;
    private double[] amatureMovementNeckY;
    private double[] amatureMovementNeckZ;
    private double[] amatureMovementShoulderCenterX;
    private double[] amatureMovementShoulderCenterY;
    private double[] amatureMovementShoulderCenterZ;
    private double[] amatureMovementShoulderLeftX;
    private double[] amatureMovementShoulderLeftY;
    private double[] amatureMovementShoulderLeftZ;
    private double[] amatureMovementElbowLeftX;
    private double[] amatureMovementElbowLeftY;
    private double[] amatureMovementElbowLeftZ;
    private double[] amatureMovementWristLeftX;
    private double[] amatureMovementWristLeftY;
    private double[] amatureMovementWristLeftZ;
    private double[] amatureMovementHandLeftX;
    private double[] amatureMovementHandLeftY;
    private double[] amatureMovementHandLeftZ;
    private double[] amatureMovementShoulderRightX;
    private double[] amatureMovementShoulderRightY;
    private double[] amatureMovementShoulderRightZ;
    private double[] amatureMovementElbowRightX;
    private double[] amatureMovementElbowRightY;
    private double[] amatureMovementElbowRightZ;
    private double[] amatureMovementHandRightX;
    private double[] amatureMovementHandRightY;
    private double[] amatureMovementHandRightZ;
    private double[] amatureMovementHipLeftX;
    private double[] amatureMovementHipLeftY;
    private double[] amatureMovementHipLeftZ;
    private double[] amatureMovementKneeLeftX;
    private double[] amatureMovementKneeLeftY;
    private double[] amatureMovementKneeLeftZ;
    private double[] amatureMovementAnkcleLeftX;
    private double[] amatureMovementAnkcleLeftY;
    private double[] amatureMovementAnkcleLeftZ;
    private double[] amatureMovementFootLeftX;
    private double[] amatureMovementFootLdeftY;
    private double[] amatureMovementFootLdeftZ;
    private double[] amatureMovementHipRightX;
    private double[] amatureMovementHipRightY;
    private double[] amatureMovementHipRightZ;
    private double[] amatureMovementKneeRightX;
    private double[] amatureMovementKneeRightY;
    private double[] amatureMovementKneeRightZ;
    private double[] amatureMovementAnkcleRightX;
    private double[] amatureMovementAnkcleRightY;
    private double[] amatureMovementAnkcleRightZ;
    private double[] amatureMovementFootRightX;
    private double[] amatureMovementFootRightY;
    private double[] amatureMovementFootRightZ;

    public List<double> expertJoint0X = new List<double>();
    public List<double> expertJoint0Y = new List<double>();
    public List<double> expertJoint0Z = new List<double>();
    public List<double> expertJoint1X = new List<double>();
    public List<double> expertJoint1Y = new List<double>();
    public List<double> expertJoint1Z = new List<double>();
    public List<double> expertJoint2X = new List<double>();
    public List<double> expertJoint2Y = new List<double>();
    public List<double> expertJoint2Z = new List<double>();
    public List<double> expertJoint3X = new List<double>();
    public List<double> expertJoint3Y = new List<double>();
    public List<double> expertJoint3Z = new List<double>();
    public List<double> expertJoint4X = new List<double>();
    public List<double> expertJoint4Y= new List<double>();
    public List<double> expertJoint4Z = new List<double>();
    public List<double> expertJoint5X = new List<double>();
    public List<double> expertJoint5Y = new List<double>();
    public List<double> expertJoint5Z = new List<double>();
    public List<double> expertJoint6X = new List<double>();
    public List<double> expertJoint6Y = new List<double>();
    public List<double> expertJoint6Z = new List<double>();
    public List<double> expertJoint7X = new List<double>();
    public List<double> expertJoint7Y = new List<double>();
    public List<double> expertJoint7Z = new List<double>();
    public List<double> expertJoint8X = new List<double>();
    public List<double> expertJoint8Y = new List<double>();
    public List<double> expertJoint8Z = new List<double>();
    public List<double> expertJoint9X = new List<double>();
    public List<double> expertJoint9Y = new List<double>();
    public List<double> expertJoint9Z = new List<double>();
    public List<double> expertJoint10X = new List<double>();
    public List<double> expertJoint10Y = new List<double>();
    public List<double> expertJoint10Z = new List<double>();
    public List<double> expertJoint11X = new List<double>();
    public List<double> expertJoint11Y = new List<double>();
    public List<double> expertJoint11Z = new List<double>();
    public List<double> expertJoint12X = new List<double>();
    public List<double> expertJoint12Y = new List<double>();
    public List<double> expertJoint12Z = new List<double>();
    public List<double> expertJoint13X = new List<double>();
    public List<double> expertJoint13Y = new List<double>();
    public List<double> expertJoint13Z = new List<double>();
    public List<double> expertJoint14X = new List<double>();
    public List<double> expertJoint14Y = new List<double>();
    public List<double> expertJoint14Z = new List<double>();
    public List<double> expertJoint15X = new List<double>();
    public List<double> expertJoint15Y = new List<double>();
    public List<double> expertJoint15Z = new List<double>();
    public List<double> expertJoint16X = new List<double>();
    public List<double> expertJoint16Y = new List<double>();
    public List<double> expertJoint16Z = new List<double>();
    public List<double> expertJoint17X = new List<double>();
    public List<double> expertJoint17Y = new List<double>();
    public List<double> expertJoint17Z = new List<double>();
    public List<double> expertJoint18X = new List<double>();
    public List<double> expertJoint18Y = new List<double>();
    public List<double> expertJoint18Z = new List<double>();
    public List<double> expertJoint19X = new List<double>();
    public List<double> expertJoint19Y = new List<double>();
    public List<double> expertJoint19Z = new List<double>();

    public List<double> amatureJoint0 = new List<double>();
    public List<double> amatureJoint1 = new List<double>();
    public List<double> amatureJoint2 = new List<double>();
    public List<double> amatureJoint3 = new List<double>();
    public List<double> amatureJoint4 = new List<double>();
    public List<double> amatureJoint5 = new List<double>();
    public List<double> amatureJoint6 = new List<double>();
    public List<double> amatureJoint7 = new List<double>();
    public List<double> amatureJoint8 = new List<double>();
    public List<double> amatureJoint9 = new List<double>();
    public List<double> amatureJoint10 = new List<double>();
    public List<double> amatureJoint11 = new List<double>();
    public List<double> amatureJoint12 = new List<double>();
    public List<double> amatureJoint13 = new List<double>();
    public List<double> amatureJoint14 = new List<double>();
    public List<double> amatureJoint15 = new List<double>();
    public List<double> amatureJoint16 = new List<double>();
    public List<double> amatureJoint17 = new List<double>();
    public List<double> amatureJoint18 = new List<double>();
    public List<double> amatureJoint19 = new List<double>();

    public void JointProgressionExpert()
    {
        expertMovementHipCenterX = expertJoint0X.ToArray();
        //continue
    }

    public void JointProgressionAmature()
    {
        amatureMovementHipCenterX = amatureJoint0.ToArray();
        //continue
    }
}
